### ISSUE TITLE
general TODOs

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/exp_CircStim#3]
### IMPORTANT
- [x] settle on a weibull fitting schema ( #5 ):
  - [x] how many trials
  - [x] whether to equalize correct and incorrect
  - [x] and the same for final fit in time shuffle part of the study
- [x] extend training
  - [x] gradual speedup
  - [x] periodical feedback info
  - [x] consider checking correctness for last `N` trials if trials in training exceed some number
  - [x] speedup info
  - [x] fix periodical feedback info - should be shown only when correctness is below treshold, if it is above - speedup info will cover correctness
- [x] finish conventions of saving data, logs etc:
  - [x] for subject **23** the file name in the contrast-varying part of the exp should be `23_c.xls` 
  - [x] for time-varying part the name should be `23_t.xls`
  - [x] training dataframe should be saved: `23_a.xls` for example
- [x] finish `t` version of experiment ( #4 ) - should load relevant data, fit psychometric function and set about `70%` correctness contrast
- [x] instructions
  - [x] clear, coherent task instructions
  - [x] info to try to respond every time (guess)
  - [x] info about fixation point
  - [ ] info about movement (including eye movements), maybe blinking
  - [x] info about breaks

### NOT CRUCIAL
- [ ] make sure that lowest contrast from `settings.py` - in `exp` dict is used everywhere instead of hardcoding values
- [x] maybe clear up `fit_weibull`, `set_opacity_if_fit_fails` and `correct_Weibull_fit`
- [x] modify training to have some breaks with info about correctness etc.

### NOT NECESSARY
- [ ] send sms to experimenter when experiment section is about to end (for example - 5 trials left)

**Comment by mmagnuski** [comment]
@msuch update'uj do woli. Z przyzwyczajenia napisałem w inglisz (bo komentarze w kodzie zwykle piszę po angielsku), ale wygodniej będzie ustalać w polisz wszystko :grinning:

**Comment by msuch** [comment]
jeśli chodzi o część time-dependent, zastanawiam się jak do tego podejść - bo z której strony bym nie zaczynał, albo mam potrzebę kopiuj-wklej, albo przeorganizowania części metod

zastanawiam się czy raczej:
- skopiować exp i odpalić nowy gabcon (gabcon_2 :)) dla nowego expa
- rozszerzyć exp o nowe klucze i przeiterować od nowa w gabconie poniżej
- pozmieniać kilka rzeczy i wprowadzić klasę przeprowadzającą badanie

popróbuję adhocowo i zobaczę które z rozwiązań da radę :)

**Comment by mmagnuski** [comment]
Jestem za pierwszym rozwiązaniem, myślę że będzie najłatwiejsze.
Myślę, że to, co potrzebujesz dodaj do `stimutils` i `settings` i przekopiuj `gabcon.py` jako `gabcon_t.py` - kilka zmian powinno dać nową procedurę.
DataFrame możesz tworzyć w `gabcon_t.py` i podawać do `present_trial` tak jak robi to `present_training`. Bo DataFrame jest tworzony w settings dla wersji `_c` ale najłatwiej będzie dla `_t` tworzyć df w głównej procedurze zamiast przedzierać się przez settings is stimutils.
